spring.application.name=spring-cloud-config-server
server.port=8888

# spring.cloud.config.server.git.uri=file:///C:/Users/Muskan/roughcode/Microservices/git-localconfig-repo
spring.cloud.config.server.git.uri=https://github.com/muskanmp/spring-cloud-microservices.git/git-localconfig-repo
# spring.cloud.config.server.git.search-paths=git-localconfig-repo
spring.cloud.config.server.git.default-label=master