spring.application.name=currency-exchange
server.port=8000
spring.config.import=optional:configserver:http://localhost:8888

spring.datasource.url=jdbc:mariadb://localhost:3306/microservicesdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver